# Generated by Django 5.2.4 on 2025-07-07 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiztaker',
            name='is_validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quiztaker',
            name='validated_score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
